module.exports = {
    NULL_VALUE: "필요한 값이 없습니다.",
    OUT_OF_VALUE: "파라미터 값이 잘못 되었습니다.",
    SIGN_UP_SUCCESS: "회원가입 성공",
    SIGN_UP_FAIL: "회원 가입 실패",
    SIGN_IN_SUCCESS: "로그인 성공",
    SIGN_IN_FAIL: "로그인 실패",
    ALREADY_ID: "존재하는 ID 입니다.",
    NO_USER: "존재하지 않는 유저 id 입니다.",
    MISS_MATCH_PW: "비밀번호가 일치하지 않습니다",
    EMPTY_TOKEN: "토큰이 없습니다",
    

    BOARD_CREATE_SUCCESS: "게시글 작성 성공",
    BOARD_CREATE_FAIL: "게시글 작성 실패",
    BOARD_READ_ALL_SUCCESS: "게시글 전체 조회 성공",
    BOARD_READ_ALL_FAIL: "게시글 전체 조회 실패",
    BOARD_READ_SUCCESS: "게시글 조회 성공",
    BOARD_READ_FAIL: "게시글 조회 실패",
    BOARD_UPDATE_SUCCESS: "게시글 수정 성공",
    BOARD_UPDATE_FAIL: "게시글 수정 실패",
    BOARD_DELETE_SUCCESS: "게시글 삭제 성공",
    BOARD_DELETE_FAIL: "게시글 삭제 실패",
    BOARD_ACTIVATE_SUCCESS: "게시글 마감설정 변경 성공",
    BOARD_ACTIVATE_FAIL: "게시글 마감설정 변경 실패",
    ALREADY_ID: "존재하는 ID 입니다.",
    NO_USER: "존재하지 않는 유저 입니다.",
    NO_BOARD: "존재하지 않은 게시글 입니다.",
    MISS_MATCH_PW: "비밀번호가 일치하지 않습니다",
    MISS_MATCH_ID: "현재 유저는 해당 게시물의 글쓴이가 아닙니다",
    INTERNAL_SERVER_ERROR: "서버 내부 오류",
    INVALID_TOKEN: "올바르지 않은 토큰",
    SEARCH_SUCCESS: "검색 성공",
    SEARCH_FAIL: "검색 실패",

    MYPAGE_READ_SUCCESS: "마이페이지 조회 성공",
    MYPAGE_READ_FAIL: "마이페이지 조회 실패",
    MYPAGE_UPDATE_SUCCESS: "마이페이지 수정 성공",
    MYPAGE_UPDATE_FAIL: "마이페이지 수정 실패",

    RECOMMEND_READ_SUCCESS: "추천 여행지 조회 성공",
    RECOMMEND_READ_FAIL: "추천 여행지 조회 실패",

    MATE_READ_SUCCESS: "위드 메이트 조회 성공",
    MATE_READ_FAIL: "위드 메이트 조회 실패",

    ACTIVATE_SUCCESS:"마감 풀기 성공",
    ACTIVATE_FALSE:"마감 풀기 실패",

    READ_REGION_LIST_SUCCESS: "국가 리스트 조회 성공",
    READ_REGION_LIST_FAIL: "국가 리스트 조회 살패",

    READ_HOME_BGIMG_SUCCESS: "홈배경 이미지 조회 성공",
    READ_HOME_BGIMG_FAIL: "홈배경 이미지 조회 실패",

    EVALUATE_SUCCESS:"동행 평가 성공",
    EVALUATE_FAIL:"동행 평가 실패",
    
    CHAT_CREATE_SUCCESS:"채팅방 생성 성공",
    CHAT_CREATE_FAIL:"채팅방 생성 실패",
    ALREADY_CHAT: "이미 채팅방이 존재합니다",

    CHAT_READ_ALL_SUCCESS:"채팅방 전체 조회 성공",
    CHAT_READ_ALL_FAIL:"채팅방 전체 조회 실패",

    WITH_SUCCESS: "동행 성공",
    WITH_FAIL: "동행 실패",

    X_NULL_VALUE: (x) => `${x}가 존재하지 않습니다.`,
    X_CREATE_SUCCESS: (x) => `${x} 작성 성공`,
    X_CREATE_FAIL: (x) => `${x} 작성 실패`,
    X_READ_ALL_SUCCESS: (x) => `${x} 전체 조회 성공`,
    X_READ_ALL_FAIL: (x) => `${x} 전체 조회 실패`,
    X_READ_SUCCESS: (x) => `${x} 조회 성공`,
    X_READ_FAIL: (x) => `${x} 조회 실패`,
    X_UPDATE_SUCCESS: (x) => `${x} 수정 성공`,
    X_UPDATE_FAIL: (x) => `${x} 수정 실패`,
    X_DELETE_SUCCESS: (x) => `${x} 삭제 성공`,
    X_DELETE_FAIL: (x) => `${x} 삭제 실패`,  
    NO_X: (x) => `존재하는 ${x} 입니다.`,
    ALREADY_X: (x) => `존재하는 ${x} 입니다.`,
}